[[redirects]]
  from = "/linkk"
  to = "/lank/linkk.html"
  status = 200
  force = true
[[redirects]]
  from = "/linkkk"
  to = "/social/linkkk.html"
  status = 200
  force = true
[[redirects]]
  from = "/linkkkk"
  to = "/links/linkkkk.html"
  status = 200
  force = true
